[General]
__userfile__=true

[clock]
showDate=false
timeFormat=HH:mm
type=clock
tzFormat=ddd

[desktopswitch]
alignment=Left
type=desktopswitch

[mainmenu]
alignment=Left
icon=/usr/share/lxqt/themes/dark/mainmenu.svg
ownIcon=true
showText=true
text=Applications
type=mainmenu

[mount]
alignment=Right
type=mount

[panel1]
alignment=0
animation-duration=0
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/usr/share/applications/qterminal.desktop
apps\3\desktop=/usr/share/applications/kbd-toggle.desktop
apps\size=3
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=96
lineCount=1
lockPanel=true
opacity=100
panelSize=128
plugins=mainmenu, quicklaunch, taskbar, tray, statusnotifier, worldclock, showdesktop
position=Bottom
reserve-space=true
show-delay=0
type=quicklaunch
visible-margin=true
width=100
width-percent=true

[quicklaunch]
alignment=Left
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/usr/share/applications/qterminal.desktop
apps\3\desktop=/usr/share/applications/kbd-toggle.desktop
apps\size=3
type=quicklaunch

[showdesktop]
alignment=Right
type=showdesktop

[statusnotifier]
alignment=Right
type=statusnotifier

[taskbar]
alignment=Left
buttonStyle=Icon
buttonWidth=240
showOnlyOneDesktop=true
type=taskbar

[tray]
alignment=Right
spacing=8
type=tray

[volume]
alignment=Right
type=volume

[worldclock]
alignment=Right
format=HH:mm
showDate=false
timeFormat=HH:mm
type=worldclock
tzFormat=
