[desktop]
wallpaper_mode=stretch
wallpaper=/usr/share/backgrounds/nx-ubuntu.png
desktop_bg=#2c001e
desktop_fg=#ffffff
desktop_font=Ubuntu 12
show_wm_menu=0
sort=mtime;ascending;
show_documents=0
show_trash=1
show_mounts=0
